### ISSUE TITLE
Post.DataAsjson is great but It is better to have Post.DataAsPlainText as well

### ISSUE THREAD

**Issue by alirezashah** [H-Ahmadi/Suzianna#2]
Hi Mr Hadi
I’m working with suzianna screenPlay to implement my test specs using specflow. It’s easy to use readable and actor centric acceptance tests.
It will be fine if you add some missing http client

**Comment by H-Ahmadi** [comment]
Hi Alireza, Thank you for your feedback.
Sending content as PlainText & XML with different verbs (POST, PUT, PATCH) will be added in the next release.
